{{- if .Values.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
  labels:
    usage: fileshare-pv
spec:
  capacity:
    storage: {{ .Values.persistentVolume.capacity }}
  #accessModes:
    #- {{ .Values.persistentVolume.accessModes }}
  accessModes: {{ toYaml .Values.persistentVolume.accessModes | nindent 4 }}

  persistentVolumeReclaimPolicy: {{ .Values.persistentVolume.reclaimPolicy }}
  azureFile:
    secretName: {{ .Values.persistentVolume.azureFile.secretName }}
    shareName: {{ .Values.persistentVolume.azureFile.shareName }}
    readOnly: {{ .Values.persistentVolume.azureFile.readOnly }}
{{- end }}

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: fileshare-pv
#   labels:
#     usage: fileshare-pv
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   azureFile:
#     secretName: azure-fileshare-secret
#     shareName: sandboxcadtpsa
#     readOnly: false
