apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: "Deployment" # Update to your pod's kind if different
    name: {{ .Release.Name }}
  updatePolicy:
    updateMode: "Auto"
